### ISSUE TITLE
Using CL-CSEN for test only

### ISSUE THREAD

**Issue by dawnlh** [meteahishali/CSENDistance#1]
Hi ~
Thanks for the nice work, I want to implement a distance estimation task based on the pretrained CL-CSEN model, and I only have test images and the object bounding boxes. I wonder if  there is any light weight code to perform the test on my data?

**Comment by meteahishali** [comment]
Hi,

Thank you for your interest in our work. The current implementation involves the following stages: feature extraction, data preprocessing, and finally regression. Although these stages are written in separate script files, they will provide a big clue if you like to combine them to use in your task. Meantime, I also plan to combine these stages in a single Python script for ease of use. Thank you for your feedback.

Best Regards,
Mete Ahishali

**Comment by dawnlh** [comment]
Thanks! Looking forward to your updating!

All the best!
Zhihong

**Comment by meteahishali** [comment]
Hi, a Demo is now available using CL-CSEN weights with end-to-end script on Python.
