### ISSUE TITLE
a bug for computing minimum samples per class

### ISSUE THREAD

**Issue by dawnlh** [meteahishali/CSENDistance#2]
Considering the case when some distance (like 50m) doesn't exist, then the following code will be wrong.
https://github.com/meteahishali/CSENDistance/blob/a4fafd137baecb796fb7de59bcefdda5ade5b313/processFeatures.m#L41-L46

I think this block should be 
```
uni_class = unique(meters_quant);
histt = zeros(length(uni_class), 1);
for i = 1:length(uni_class)
   histt(i) = sum(meters_quant == uni_class(i));
end
eqSize = min(histt);
```

**Comment by meteahishali** [comment]
Right, this is now fixed. Thank you for the feedback!
