### ISSUE TITLE
Bug for visualization the CRC results

### ISSUE THREAD

**Issue by dawnlh** [meteahishali/CSENDistance#3]
https://github.com/meteahishali/CSENDistance/blob/79627ebc79b6ea69bd543ae56c7f2885984bdd3e/processFeatures.m#L204-L206

perhaps this block should be
```
scatter(y_trues(k, :), y_preds(k, :), 3, 'filled'), 
title(strcat('Collaborative Filtering, MSE: ', ... 
num2str(sum((y_trues(k, :)- y_preds(k, :)).^2)/length(y_trues(k, :)))))
```
As test.label is the index  of the distance, not the distance itself.

**Comment by dawnlh** [comment]
By the way, is there any code for the result visualization as shown in Fig.9. of the paper? Thanks a lot if you can share it!

**Comment by meteahishali** [comment]
> https://github.com/meteahishali/CSENDistance/blob/79627ebc79b6ea69bd543ae56c7f2885984bdd3e/processFeatures.m#L204-L206
> 
> perhaps this block should be
> 
> ```
> scatter(y_trues(k, :), y_preds(k, :), 3, 'filled'), 
> title(strcat('Collaborative Filtering, MSE: ', ... 
> num2str(sum((y_trues(k, :)- y_preds(k, :)).^2)/length(y_trues(k, :)))))
> ```
> 
> As test.label is the index of the distance, not the distance itself.

I will make the required modification in the referenced block. In the current implementation, as the quantization level is already a meter, this does not have an effect on the scattering plot (labels correspond to meters). However, it will be an issue with a different quantization level is used, for example, 0.5m or 2m etc. I will make the implementation more generic in the next update.

> By the way, is there any code for the result visualization as shown in Fig.9. of the paper? Thanks a lot if you can share it!

For the bounding box visualization, I followed a very similar approach to https://github.com/harshilpatel312/KITTI-distance-estimation . You can check for instance prediction-visualizer.py and visualizer.py.

**Comment by dawnlh** [comment]
Got it, thanks a lot!
