### ISSUE TITLE
Run the model on my own data

### ISSUE THREAD

**Issue by SaharGezer** [meteahishali/CSENDistance#5]
I want to know if there is an option to run this model on my open dataset?

Thank you

**Comment by meteahishali** [comment]
Hi,

Thank you for the question. Yes, you can run the methods on your own dataset. You just need to follow the specified steps: 1. feature extraction with feature_extraction.py script, 2. running crc/main.m script for the CRC method for the coarse estimation, and 3. running CL-CSEN or CSEN method using regressor_main.py script.

**Comment by SaharGezer** [comment]
Hi, 
I did not understand where can I put the path to my own data?

Thank you

**Comment by meteahishali** [comment]
Hi,

You can specify the folder where you store your frames at line number 26 of feature_extraction.py script:
`imagePath = kittiData + 'training/image_2/'`
In line number 27 of the same script, you need to specify the corresponding ground-truth data consisting of object bounding box locations and their distances to the camera. I store them in a CSV file, but you can of course change the format:
`df = pd.read_csv(kittiData + 'annotations.csv')`
